### PR TITLE
Upgrade OkHttp from 2 to 3

### PR DESCRIPTION
**Pull request by jvanderwee**

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks! Can you sign our CLA: https://github.com/snowplow/snowplow/wiki/CLA

**Comment by jvanderwee** [comment]
Signed!

**Comment by alexanderdean** [comment]
Confirmed! Thanks so much. Assigning to @jbeemster to review...

**Comment by beetlebum** [comment]
@alexanderdean what is the status of this branch, when do you plan to release it?
We've migrated our app to okhttp3 and this is the only dependency that still requires okhttp2, so we're bundling both in our app.
Please let me know if I can help somehow.

**Comment by alexanderdean** [comment]
Hey @jbeemster - we discussed the scheduling for this recently (goal was to time this to avoid forcing people to upgrade prematurely). I thought we had put a date on when we were going to merge this in but I can't see it?

**Comment by jvanderwee** [comment]
Any updates on this?

**Comment by alexanderdean** [comment]
Let's put this into the next version...

**Comment by MoizAli** [comment]
@alexanderdean any idea when the next version is being released?

**Comment by alexanderdean** [comment]
It will be within the next 3 weeks...

**Comment by jvanderwee** [comment]
Any updates on this release?

**Comment by MoizAli** [comment]
@alexanderdean it still isn't available yet. Any idea when the new release would be?

**Comment by MoizAli** [comment]
@alexanderdean looks like its still open. Can we get an estimate on this?

**Comment by jbeemster** [comment]
Hi @jvanderwee @MoizAli, sorry for the delay on this!  We are hoping to have this out early next week.

**Comment by bogaert** [comment]
Any updates on this?

**Comment by jbeemster** [comment]
Hi @bogaert this is pending review by @alexanderdean before release.  An M1 has been pushed for those keen to get started:

`compile 'com.snowplowanalytics:snowplow-android-tracker:0.6.0-M1@aar'`

**Pull request closed without merging**
